config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin'
  namespace :admin do
    resources :users

    get '/', to: 'users#index'
  end

  devise_for :users, skip: :all

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        scope '/', defaults: { format: :json } do
          post   'users/sign_in',  to: 'account/sessions#create'
          delete 'users/sign_out', to: 'account/sessions#destroy'
          post   'users/sign_up',  to: 'account/registrations#create'
          put    'account',        to: 'account/registrations#update'
          delete 'account',        to: 'account/registrations#destroy'
          get    'account',        to: 'account/registrations#edit'
        end
      end

      resources :users, only: %i[index show]
    end
  end

  root 'admin/users#index'
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jwt_blacklist.rb
# frozen_string_literal: true

class JwtBlacklist < ApplicationRecord
  include Devise::JWT::RevocationStrategies::Blacklist

  self.table_name = 'jwt_blacklist'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtBlacklist

  mount_uploader :avatar, AvatarUploader
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < ApplicationController
    before_action :authenticate_admin_user!
    before_action :set_user, only: %i[show edit update destroy]
    before_action :set_new_user, only: %i[new create]
    before_action :set_form_user, only: %i[new edit create update]

    def index
      respond_to do |format|
        format.html
        format.json do
          users = UsersListQuery.new(User.all, order_params: order_params).call
          scope = UsersSearchQuery.new(users, params[:search]).call
          render json: DataTable::PrepareUsers.new(scope, params).prepare_json.to_json
        end
      end
    end

    def show; end

    def edit; end

    def new; end

    def create
      result = Users::Create.call(user: @user, params: user_params)
      if result.success?
        flash[:success] = "Пользователь #{@user.name} успешно создан!"
        redirect_to admin_user_path(@user)
      else
        flash[:danger] = 'Пожалуйста, исправьте ошибки указанные ниже'
        render :new
      end
    end

    def update
      result = Users::Update.call(user: @user, params: user_params)
      if result.success?
        flash[:success] = 'Инофрмация о пользователе обновлена'
        redirect_to admin_user_path(@user)
      else
        flash[:danger] = 'Пожалуйста, исправьте ошибки указанные ниже'
        render :edit
      end
    end

    def destroy
      @user.destroy
      redirect_to(admin_users_path)
    end

    private

    def order_params
      DataTableParams.new(params).order_params
    end

    def user_params
      params.require(:user).permit(:name, :email, :avatar, :password, :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id]).decorate
    end

    def set_new_user
      @user = User.new
    end

    def set_form_user
      @user = UserForm.new(@user)
    end
  end
end

app/controllers/api/v1/account/registrations_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Account
      class RegistrationsController < Devise::RegistrationsController
        protect_from_forgery with: :null_session
        before_action :configure_account_update_params, only: :update
        skip_before_action :verify_authenticity_token, only: :create

        include Response
        include ExceptionHandler

        def edit
          json_response(resource)
        end

        def create
          build_resource(sign_up_params)

          resource.save
          render_resource(resource)
        end

        def update
          result = Users::Update.call(user: UserForm.new(resource), params: account_update_params)
          render_resource(result.user)
        end

        protected

        def configure_account_update_params
          devise_parameter_sanitizer.permit(:account_update, keys: %i[name avatar])
        end
      end
    end
  end
end

app/controllers/api/v1/account/sessions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module Account
      class SessionsController < Devise::SessionsController
        skip_before_action :verify_authenticity_token
        include ExceptionHandler

        private

        def respond_with(resource, _opts = {})
          render json: resource
        end

        def respond_to_on_destroy
          head :no_content
        end
      end
    end
  end
end

app/controllers/api/v1/base_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class BaseController < ActionController::API
      before_action :authenticate_user!
      respond_to :json

      include Response
      include ExceptionHandler
    end
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class UsersController < BaseController
      def index
        json_response(User.all)
      end

      def show
        user = User.find(params[:id])
        json_response(user)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/exception_handler.rb
# frozen_string_literal: true

module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ errors: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ errors: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/concerns/response.rb
# frozen_string_literal: true

module Response
  def json_response(obj, status = :ok)
    render json: obj, serializer: UserSerializer, status: status
  end

  def render_resource(resource)
    if resource.valid?
      render json: { status: :success, data: resource }, status: :ok
    else
      validation_error(resource)
    end
  end

  def validation_error(resource)
    render json: {
      status: :error,
      errors: resource.errors
    }, status: :unprocessable_entity
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def body_data_page
    (params[:controller].split('/') << action_name).map(&:camelize).join
  end
end

app/views/admin/users/_form.html.slim
= simple_form_for [:admin, @user] do |f|
  .row.row-xs.align-items-center.mg-b-20
    .col-md-12.mg-t-5
      = f.input :name, input_html: { class: 'form-control' }
    .col-md-12.mg-t-5
      = f.input :avatar, as: :file, input_html: { class: 'form-control' }
    .col-md-12.mg-t-5
      = f.input :email, input_html: { class: 'form-control' }
    .col-md-12.mg-t-5
      = f.input :password, input_html: { class: 'form-control' }
    .col-md-12.mg-t-5
      = f.input :password_confirmation, input_html: { class: 'form-control' }

  .row.row-xs.align-items-center.mg-b-2
    = f.submit 'Сохранить', class: 'btn btn-success'
    = link_to 'Отменить', admin_users_path, class: 'btn btn-secondary mg-l-15'

app/views/admin/users/edit.html.slim
= render 'form'

app/views/admin/users/index.html.slim
= link_to 'Создать пользователя', new_admin_user_path, class: 'btn btn-az-primary mg-b-20'

.dataTables_wrapper
  table#users_table.table.dataTable.datatable.mg-b-0[ data-url="#{admin_users_path}" ]
    thead
      tr
        th ID
        th Имя
        th Email
        th Дата создания
        th Дата обновления
    tbody

app/views/admin/users/new.html.slim
= render 'form'

app/views/admin/users/show.html.slim
= link_to 'Редактировать пользователя', edit_admin_user_path(@user), class: 'btn btn-primary mb-5'

= link_to 'Удалить пользователя',
          admin_user_path(@user),
          method: :delete,
          class: 'btn btn-danger mg-l-10 mb-5',
          data: { confirm: 'Вы уверены?' }

.card
  .card-header
    .card-title.mg-b-0 Пользователь
  .card-body
    .row
      .col-12#user-details
        .az-content-body.az-content-body-invoice.ps--active-y
          .card.card-invoice
            .card-body
              .col-12.mg-b-15
                .az-img-user.avatar-xxl
                  = @user.display_avatar
                h4.mg-t-15.az-content-label = @user.name
              .invoice-header
                .col-12
                  p.invoice-info-row
                    = @user.generate_i18n(User, :email, @user.email)
                  p.invoice-info-row
                    = @user.generate_i18n(User, :created_at, @user.display_created_at)
                  p.invoice-info-row
                    = @user.generate_i18n(User, :updated_at, @user.display_updated_at)

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TestApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.az-body.az-light[data-page=body_data_page]
    = render 'shared/navbar'
    .az-content.az-content-dashboard
      .container
        .az-content-body
          = render 'shared/flash'
          = yield

app/views/layouts/devise.html.slim
doctype html
html lang="ru"
  head
    title Авторизация
    meta charset='utf-8'
    meta content='width=device-width, initial-scale=1, shrink-to-fit=no' name='viewport'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.az-body
    .az-body
      = yield

app/views/shared/_flash.html.slim
- flash.each do |name, value|
  .alert.mg-b-15 class="alert-#{name}" role='alert'
    button.close aria-label='Close' data-dismiss='alert' type='button'
      span aria-hidden='true'  ×
    = value

app/views/shared/_navbar.html.slim
.az-header
  .container
    .az-header-left
      = link_to root_path, class: 'az-logo' do
        span
        | TestApp
      #azMenuShow.az-header-menu-icon.d-lg-none
        span

    .az-header-menu
      ul.nav
        li.nav-item
          a.nav-link.with-sub href='javascript:;'  Обзор
          .az-menu-sub
            nav.nav
             a.nav-link href='javascript:;' Dashboard

    .az-header-right
      .dropdown.az-profile-menu
        a.az-img-user href='javascript:;'
          img alt='avatar' src='https://via.placeholder.com/500'
        .dropdown-menu
          .az-dropdown-header.d-sm-none
            a.az-header-arrow href='javascript:;'
              i.icon.ion-md-arrow-back
          .az-header-profile
            .az-img-user
              img alt='avatar' src='https://via.placeholder.com/500'
            span = current_admin_user.email
            span Admin
          = link_to destroy_admin_user_session_path, class: 'dropdown-item', method: :delete do
            i.typcn.typcn-power-outline
            | Выйти

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  .row.row-xs.align-items-center.mg-b-20
    .col-md-12.mg-t-5
      = f.input :name, input_html: { class: 'form-control' }
    .col-md-12.mg-t-5
      = f.input :avatar, as: :file, input_html: { class: 'form-control' }
    .col-md-12.mg-t-5
      = f.input :email, input_html: { class: 'form-control' }
    .col-md-12.mg-t-5
      = f.input :password, input_html: { class: 'form-control' }
    .col-md-12.mg-t-5
      = f.input :password_confirmation, input_html: { class: 'form-control' }

  .row.row-xs.align-items-center.mg-b-2
    = f.submit 'Сохранить', class: 'btn btn-success'
    = link_to 'Отменить', users_path, class: 'btn btn-secondary mg-l-15'

app/views/users/show.html.slim
= link_to 'Редактировать пользователя', edit_user_path(@user), class: 'btn btn-primary mb-5'

= link_to 'Удалить пользователя',
          user_path(@user),
          method: :delete,
          class: 'btn btn-danger mg-l-10 mb-5',
          data: { confirm: 'Вы уверены?' }

.card
  .card-header
    .card-title.mg-b-0 Пользователь
  .card-body
    .row
      .col-12#user-details
        .az-content-body.az-content-body-invoice.ps--active-y
          .card.card-invoice
            .card-body
              .col-12.mg-b-15
                .az-img-user.avatar-xxl
                  = @user.display_avatar
                h4.mg-t-15.az-content-label = @user.name
              .invoice-header
                .col-12
                  p.invoice-info-row
                    = @user.generate_i18n(User, :email, @user.email)
                  p.invoice-info-row
                    = @user.generate_i18n(User, :created_at, @user.display_created_at)
                  p.invoice-info-row
                    = @user.generate_i18n(User, :updated_at, @user.display_updated_at)